
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com:
      minden:
        ai:
          scm: TRACE
    org:
      springframework:
          security:
            web: TRACE


springdoc:
  packages-to-scan: com.minden.ai.scm.controller
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    path: /swagger-ui
  api-docs:
    path: /api-docs

spring:
  profiles:
    active: ${ACTIVE_PROFILE}:dev
  application:
    name: scms
