version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: msd@123
      MYSQL_DATABASE: scms
      MYSQL_USER: user
      MYSQL_PASSWORD: msd@123
    ports:
      - 3306:3306

  app:
    image: Docker
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/scms
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: msd@123
      ACTIVE_PROFILE: prod
